### ISSUE TITLE
Investigate update of manifest via Github Actions

### ISSUE THREAD

**Issue by jasperslits** [jasperslits/haithowifi#23]
Investigate update of manifest.json via Github Actions upon creation of new tag.

**Comment by benjamin-dcs** [comment]
Here’s a GitHub Action workflow file that will trigger on the creation of a new tag in the format `vx.y`, extract the version number, and update the `manifest.json` file with this version:

```yaml
name: Update Version in Manifest

on:
  push:
    tags:
      - 'v*.*'  # Matches tags in the format "vx.y"

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Get version from tag
      id: get_version
      run: |
        # Extracts the version number from the tag (e.g., "v1.2" -> "1.2")
        VERSION="${GITHUB_REF##*/}"
        VERSION="${VERSION#v}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Update version in manifest.json
      run: |
        # Read manifest.json, update the version, and overwrite the file
        jq ".version = \"$VERSION\"" manifest.json > manifest_tmp.json
        mv manifest_tmp.json manifest.json

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add manifest.json
        git commit -m "Update version to $VERSION"
        git push
```

### Explanation of the Steps
1. **Check out repository**: Checks out the code from the repository so we can work with `manifest.json`.
2. **Get version from tag**: Extracts the version number from the tag (`vx.y`) by removing the `v` prefix. The result is stored as an environment variable `VERSION`.
3. **Update version in manifest.json**: Uses `jq` to parse `manifest.json` and set the `version` field to the extracted version. The updated content is saved back to `manifest.json`.
4. **Commit changes**: Configures Git, commits the updated `manifest.json`, and pushes the change to the repository.

Make sure `manifest.json` is already in the repository so that the action can update it. This workflow assumes `jq` is available in the runner, which it is by default on GitHub's Ubuntu runners.

**Comment by benjamin-dcs** [comment]
I'd say we don't let it commit automatically though

**Comment by jasperslits** [comment]
Agree. It could make a new PR instead.

**Comment by benjamin-dcs** [comment]
Doesn't seem to be possible right now. GitHub Action won't trigger on the creation of a draft release:
- https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release
- https://github.com/orgs/community/discussions/7118

For future reference, this seems to be working code, except the trigger part:
```yaml
name: Update version in manifest.json

# on:
#   push:
#     tags:
#       - 'v*.*'  # Matches tags in the format "vx.y"

on:
  release:
    types: [created]

jobs:
  update-manifest:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    # Only run for draft releases. 
    # For published release it's too late to update the manifest file
    if: github.event.release.draft == true

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Get version from release
      id: get_version
      run: |
        # Extracts the version number from the tag (e.g., "v1.2" -> "1.2")
        # VERSION="${GITHUB_REF##*/}"
        VERSION="${{ github.event.release.tag_name }}"
        VERSION="${VERSION#v}"
        BRANCH="update-manifest-${VERSION//./-}"
        echo "$VERSION"
        echo "$BRANCH"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV

    - name: Create and switch to new branch
      run: |
        git checkout -b "$BRANCH"

    - name: Update version in manifest.json
      run: |
        # Read manifest.json, update the version, and overwrite the file
        jq ".version = \"$VERSION\"" custom_components/ithodaalderop/manifest.json > custom_components/ithodaalderop/manifest_tmp.json
        mv custom_components/ithodaalderop/manifest_tmp.json custom_components/ithodaalderop/manifest.json

    - name: Commit changes to local branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add custom_components/ithodaalderop/manifest.json
        git commit -m "Update manifest version to $VERSION"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin "$BRANCH"

    - name: Create pull request
      run: |
        gh pr create \
          --title "Update manifest version to $VERSION" \
          --body "This PR updates the manifest version." \
          --base main \
          --head "$BRANCH"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

@jasperslits I'd say we close the branch, PR and this issue. Only alternative seems to be to manually trigger a action (which could then create a update-manifest PR + draft release).
