### ISSUE TITLE
[Discussion] Add MQTT fan?

### ISSUE THREAD

**Issue by benjamin-dcs** [jasperslits/haithowifi#6]
Add MQTT fan to repo? Would be nice if this integration had al entities mentioned on the wiki right?

My current mqtt fan:

**configuration.yaml:**
`mqtt: !include_dir_merge_list mqtt`

**/mqtt/fan.yaml**:
```yaml
- fan:
    - name: "Itho HRU 350 eco"
      unique_id: f8be29e7-363a-4cdf-a5b1-aeb8e170ec49
      device:
        identifiers: "mv"
        name: "Itho Box"
        manufacturer: "Itho Daalderop"
        model: "Itho HRU 350 eco"
        # ip adres van de wifi add-on
        configuration_url: "http://192.168.107.11"
      state_topic: "ithohru/lwt"
      state_value_template: "{% if value == 'online' %}ON{% else %}OFF{% endif %}"
      command_topic: "ithohru/cmd"
      preset_mode_state_topic: "ithohru/ithostatus"
      preset_mode_command_template: >
        {% set preset_to_mode = {
          "Low": "low",
          "Medium": "medium",
          "High": "high",
          "Auto": "auto",
          "Autonight": "autonight",
          "Timer 10": "timer1",
          "Timer 20": "timer2",
          "Timer 30": "timer3",
          "Timer": "timer"
          }
        %}
        { vremote: '{{ preset_to_mode[value] }}' }
      preset_mode_value_template: >
        {% set am = value_json['Actual Mode'] | int %}
        {% if am == 1 %}
          Low
        {% elif am == 2 %}
          Medium 
        {% elif am == 3 %}
          High
        {% elif am == 13 %}
          Timer
        {% elif am == 24 %}
          Auto
        {% elif am == 25 %}
          Autonight
        {% else %}
          {{ am }}
        {% endif %}
      preset_mode_command_topic: "ithohru/cmd"
      preset_modes:
        - Low
        - High
        - Auto
        - Timer 10
        - Timer 20
        - Timer 30
        - Timer
```
